### ISSUE TITLE
为什么引入vue组件会报错？

### ISSUE THREAD

**Issue by FxPixels** [xxxsimons/mpvue-vant#10]
```
 ERROR  Failed to compile with 1 errors11:45:50

 error  in ./src/pages/index/index.vue

Module build failed: Error: Final loader didn't return a Buffer or String
    at runLoaders (D:\Project\mpvue-vant\demo\node_modules\webpack\lib\NormalModule.js:204:46)
    at D:\Project\mpvue-vant\demo\node_modules\loader-runner\lib\LoaderRunner.js:370:3
    at iterateNormalLoaders (D:\Project\mpvue-vant\demo\node_modules\loader-runner\lib\LoaderRunner.js:211:10)
    at iterateNormalLoaders (D:\Project\mpvue-vant\demo\node_modules\loader-runner\lib\LoaderRunner.js:218:10)
    at D:\Project\mpvue-vant\demo\node_modules\loader-runner\lib\LoaderRunner.js:233:3
    at Object.context.callback (D:\Project\mpvue-vant\demo\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at compileWxml.call.then.catch (D:\Project\mpvue-vant\demo\node_modules\mpvue-loader\lib\template-compiler\index.js:99:12)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)

 @ ./src/pages/index/index.vue 10:0-329
 @ ./src/pages/index/main.js
```

**Comment by FxPixels** [comment]
```
 ERROR  Failed to compile with 1 errors11:45:50

 error  in ./src/pages/index/index.vue

Module build failed: Error: Final loader didn't return a Buffer or String
    at runLoaders (D:\Project\mpvue-vant\demo\node_modules\webpack\lib\NormalModule.js:204:46)
    at D:\Project\mpvue-vant\demo\node_modules\loader-runner\lib\LoaderRunner.js:370:3
    at iterateNormalLoaders (D:\Project\mpvue-vant\demo\node_modules\loader-runner\lib\LoaderRunner.js:211:10)
    at iterateNormalLoaders (D:\Project\mpvue-vant\demo\node_modules\loader-runner\lib\LoaderRunner.js:218:10)
    at D:\Project\mpvue-vant\demo\node_modules\loader-runner\lib\LoaderRunner.js:233:3
    at Object.context.callback (D:\Project\mpvue-vant\demo\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at compileWxml.call.then.catch (D:\Project\mpvue-vant\demo\node_modules\mpvue-loader\lib\template-compiler\index.js:99:12)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)

 @ ./src/pages/index/index.vue 10:0-329
 @ ./src/pages/index/main.js
```

**Comment by xxxsimons** [comment]
引入vue组件是啥意思，不是引入vant组件嘛？是什么组件， 组件代码贴一下

**Comment by xxxsimons** [comment]
@FxPixels 引入vue组件啥意思？你引入了啥组件，代码贴一下。

**Comment by FxPixels** [comment]
[http://pd8mstw11.bkt.clouddn.com/%E4%B8%8B%E8%BD%BD.png](url)

[http://pd8mstw11.bkt.clouddn.com/%E4%B8%8B%E8%BD%BD%20%281%29.png](url)

[http://pd8mstw11.bkt.clouddn.com/%E4%B8%8B%E8%BD%BD%20%282%29.png](url)

**Comment by xxxsimons** [comment]
<header>标签是一个h5的标签，所以不要直接使用<header><header/> 

可以这样引入和使用

```html
    <vue-header></vue-header>
```
``` js
<script>
import VueHeader from "@/components/Header"
export default {
components: {
    VueHeader
  }
}
```

**Comment by FxPixels** [comment]
@xxxsimons 突然想起来…感谢…
然后，如果Header.vue再引入vant组件应该怎么做？

**Comment by xxxsimons** [comment]
@FxPixels 那看你要在哪个页面使用`vant`组件了。比如你在首页使用了`Header`，那你想在`Header`中使用vant组件的话，那就再首页的`main.json`中引入vant组件就好了。要是你在另外一个页面使用了`Header`，那你应该在对应的页面目录下的`main.json`中引入vant组件

**Comment by FxPixels** [comment]
总之就是不能在 

> Header.vue

 对应目录下 新建一个 

> main.json

 来引入vant组件对吗？

**Comment by xxxsimons** [comment]
@FxPixels 是的

**Comment by FxPixels** [comment]
@xxxsimons 我建议再把那个demo完善一下，可能不太懂怎么引用和套嵌组件。之前用mpvue-iview-weapp的时候可以直接在vue组件里加入iview组件。另外可以加入vuex。

**Comment by xxxsimons** [comment]
@FxPixels  谢谢建议! 写这个demo是供大家参考如何使用，不建议直接用demo来搭建自己的项目。vuex的话mpvue初始化项目的时候可以选择是否配置vuex。

看了一下你说的那个项目，它可以直接在组件中使用是因为它用vue改写了iview组件库（iview和vant这类组件库都是原生组件库）。我目前也打算用vue语法改写vant组件库，但是因为vant更新比较频繁所以暂时是直接使用原生组件。

**Comment by FxPixels** [comment]
目前要vue组件和vant组件组合起来的话…貌似只能够用slot…

**Comment by xxxsimons** [comment]
@FxPixels 是的 slot很坑
