### ISSUE TITLE
急急急，toast 组件引入成功，调用的时候出现下面的错误

### ISSUE THREAD

**Issue by RajanZhan** [xxxsimons/mpvue-vant#25]
前期的引入工作，在main.json中引入，在页面组件中import 成功

调用
Toast.success('test‘);

报错：
thirdScriptError
Cannot read property 'setData' of null; [Component] Event Handler Error @ pages/index/main#bound handleProxy
TypeError: Cannot read property 'setData' of null
    at Toast (http://127.0.0.1:46046/appservice/pages/index/main.js:282:10)
    at Function.success (http://127.0.0.1:46046/appservice/pages/index/main.js:299:14)
    at Vue$3.clickHandle (http://127.0.0.1:46046/appservice/pages/index/main.js:175:83)
    at Vue$3.boundFn [as clickHandle] (http://127.0.0.1:46046/appservice/common/vendor.js:190:33)
    at Array.click (http://127.0.0.1:46046/appservice/pages/index/main.js:342:15)
    at Vue$3.handleProxyWithVue [as $handleProxyWithVue] (http://127.0.0.1:46046/appservice/common/vendor.js:5235:36)
    at c.handleProxy (http://127.0.0.1:46046/appservice/common/vendor.js:4877:32)
    at Object.o.safeCallback (http://127.0.0.1:46046/appservice/__dev__/WAService.js:15:19538)
    at http://127.0.0.1:46046/appservice/__dev__/WAService.js:18:2442
    at p (http://127.0.0.1:46046/appservice/__dev__/WAService.js:18:4713)

**Comment by xxxsimons** [comment]
@RajanZhan 打开开发者助手`ES6转ES5`功能

**Comment by RajanZhan** [comment]
@xxxsimons 

代码：
<template>
  <div class="" >

	<van-button @click="clickHandle()" type="warning">vant 按钮组件 </van-button>
	
  </div>
</template>

<script>
import Toast from '@/../static/vant/toast/toast';
export default {
  data () {
    return {
      motto: 'Hello World',
      userInfo: {}
    }
  },

  components: {

  },


  methods: {
 
    clickHandle () {;
		console.log("toast is ",Toast);
		
		Toast.success('成功文案');
		console.log('clickHandle:', msg, ev)
    }
  },
}
</script>

打印的日志：
app created and cache logs by setStorageSync
index.vue:29 toast is  ƒ Toast(options) {
      if (options === void 0) {
        options = {};
      }

      options = _extends({}, currentOptions, parseOptions(options));
      var pages = getCurrentPages();
      var ctx…
VM4022:1 thirdScriptError
Cannot read property 'setData' of null; [Component] Event Handler Error @ pages/index/main#bound handleProxy
TypeError: Cannot read property 'setData' of null
    at Toast (http://127.0.0.1:46046/appservice/pages/index/main.js:173:12)
    at Function.success (http://127.0.0.1:46046/appservice/pages/index/main.js:190:16)
    at Vue$3.clickHandle (http://127.0.0.1:46046/appservice/pages/index/main.js:113:85)
    at Vue$3.boundFn [as clickHandle] (http://127.0.0.1:46046/appservice/common/vendor.js:191:80)
    at Array.click (http://127.0.0.1:46046/appservice/pages/index/main.js:263:17)
    at Vue$3.handleProxyWithVue [as $handleProxyWithVue] (http://127.0.0.1:46046/appservice/common/vendor.js:5236:38)
    at c.handleProxy (http://127.0.0.1:46046/appservice/common/vendor.js:4878:34)
    at Object.o.safeCallback (http://127.0.0.1:46046/appservice/__dev__/WAService.js:15:19538)
    at http://127.0.0.1:46046/appservice/__dev__/WAService.js:18:2442
    at p (http://127.0.0.1:46046/appservice/__dev__/WAService.js:18:4713)
console.error @ VM4022:1
errorReport @ WAService.js:4
thirdErrorReport @ WAService.js:4
(anonymous) @ WAService.js:4
(anonymous) @ WAService.js:17
o.safeCallback @ WAService.js:15
o.call @ WAService.js:15
i @ WAService.js:15
o.safeCallback @ WAService.js:15
(anonymous) @ WAService.js:18
p @ WAService.js:18
(anonymous) @ WAService.js:18
n @ WAService.js:6
e @ appservice?t=1540618189609:3280
r.registerCallback.t @ appservice?t=1540618189609:3280
l.forEach.t @ appservice?t=1540618189609:3280
(anonymous) @ appservice?t=1540618189609:3280
i.onmessage @ appservice?t=1540618189609:3280

**Comment by xxxsimons** [comment]
@RajanZhan 语法问题
```
<van-button @click="clickHandle()" type="warning">vant 按钮组件 </van-button>
// 改成
<van-button @click="clickHandle" type="warning">vant 按钮组件 </van-button>
```

先检查过自己代码的问题再去问别人问题吧，这个仓库我也写了`demo`的。

**Comment by RajanZhan** [comment]
@xxxsimons  
<van-button @click="clickHandle()" type="warning">vant 按钮组件 </van-button>
这里是没问题的，我加上括号是要传参数，现在只是参数没写。
我改成了您的
<van-button @click="clickHandle" type="warning">vant 按钮组件 </van-button>
依旧还是报错，我现在把代码上传到github，这里就是一个简单的demo，几行代码，您clone下来跑一下就看到报错了。git@github.com:RajanZhan/mpvue-vant-demo.git
最后，非常感谢您的回答。开源软件需要您的奉献精神。

**Comment by xxxsimons** [comment]
@RajanZhan 看了一下，你代码忘记加`<van-toast id="van-toast" />` 这个标签了。

参考使用文档:[https://youzan.github.io/vant-weapp/#/toast](https://youzan.github.io/vant-weapp/#/toast)

**Comment by RajanZhan** [comment]
@xxxsimons

惭愧！ o(╥﹏╥)o。
再次感谢。

**Comment by xxxsimons** [comment]
@RajanZhan  加油
